name: deploy project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test
  
      - name: build project
        run: npm run build

      - name: deploy project
        run: echo "Deploying project..."
